config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'congestions#index'
  resources :congestions do
    resources :comments, only: [:create, :destroy]
    resources :solutions, only: [:create, :destroy]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :congestion

  validates :content, presence: true
end

app/models/congestion.rb
class Congestion < ApplicationRecord
  with_options presence: true do
  validates :ski_resort_id, numericality: { other_than: 0 , message: "can't be blank"}
  validates :waiting
  validates :latitude
  validates :longitude
  end

  validates :waiting, numericality: { only_interger: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 999 }

  with_options numericality: true do
    validates :latitude
    validates :longitude
  end

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :solutions, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :ski_resort

  def solved_by?(user)
    solutions.where(user_id: user.id).exists?
  end
end

app/models/ski_resort.rb
class SkiResort < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: 'チャオ御岳スキーリゾート' },
    { id: 2, name: 'ダイナランド' },
    { id: 3, name: '高鷲スノーパーク' },
    { id: 4, name: 'ホワイトピアたかす' },
    { id: 5, name: 'めいほうスキー場' },
    { id: 6, name: 'ウイングヒルズ白鳥リゾート' },
    { id: 7, name: 'ひるがの高原スキー場' },
    { id: 8, name: '鷲ヶ岳スキー場' },
    { id: 9, name: 'スターシュプール緑風リゾート ひだ流葉' },
    { id: 10, name: '飛騨かわいスキー場' },
    { id: 11, name: 'ひだ舟山スノーリゾートアルコピア' },
    { id: 12, name: '平湯温泉スキー場' },
    { id: 13, name: '飛騨ほおのき平スキー場' },
    { id: 14, name: 'モンデウス飛騨位山スノーパーク' },
  ]

  include ActiveHash::Associations
  has_many :congestions
  end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :user
  belongs_to :congestion
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :congestions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :solutions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @congestion = Congestion.find(params[:congestion_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to congestion_path(@comment.congestion)
    else
      render "congestions/show"
    end
  end

  def destroy
    @congestion = Congestion.find(params[:congestion_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to congestion_path
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, congestion_id: params[:congestion_id])
  end
end

app/controllers/congestions_controller.rb
class CongestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @congestions = Congestion.order("created_at DESC")
  end

  def new
    @congestion = Congestion.new
  end

  def create
    @congestion = Congestion.new(congestion_params)
    if @congestion.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @congestion = Congestion.find(params[:id])
    @user = User.new
    @comment = Comment.new
    @comments = @congestion.comments.includes(:user)
  end

  def edit
    @congestion = Congestion.find(params[:id])
    unless @congestion.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def update
  @congestion = Congestion.find(params[:id])
    if @congestion.update(congestion_params)
      redirect_to congestion_path, method: :get
    else
      render :edit
    end
  end

  def destroy
    @congestion = Congestion.find(params[:id])
    @congestion.destroy
    redirect_to root_path
  end

  private
  def congestion_params
    params.require(:congestion).permit(:ski_resort_id, :situation, :waiting, :latitude, :longitude, :image).merge(user_id: current_user.id)
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def create
    @congestion = Congestion.find(params[:congestion_id])
    solution = current_user.solutions.new(congestion_id: @congestion.id)
    solution.save
    redirect_to congestion_path(@congestion)
  end

  def destroy
    @congestion = Congestion.find(params[:congestion_id])
    solution = current_user.solutions.find_by(congestion_id: @congestion.id)
    solution.destroy
    redirect_to congestion_path(@congestion)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @congestions = @user.congestions.order("created_at DESC")
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/congestions_helper.rb
module CongestionsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/congestions/edit.html.erb
<script>
function test() {
    navigator.geolocation.getCurrentPosition(test2);
}
function test2(position) {
    var geo_text = "緯度:" + position.coords.latitude + "\n";
        geo_text += "経度:" + position.coords.longitude + "\n";
        alert(geo_text);
        document.getElementById( "congestion-latitude" ).value = position.coords.latitude ;
        document.getElementById( "congestion-longitude" ).value = position.coords.longitude ;
}
</script>
<body>
  <div class="main">
    <div class="container px-4 py-5" id="custom-cards">
      <h2 class="pb-2 border-bottom">スタック情報を編集</h2>
      <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <button onclick="test()">現在地を取得する</button>
      <%= form_with model: @congestion, local: true do |f| %>
      <%= f.text_field :latitude, class:"latitude-input", id:"congestion-latitude" %>
      <%= f.text_field :longitude, class:"longitude-input", id:"congestion-longitude" %>

      <%# スキー場名 %>
        <div class="weight-bold-text">
          スキー場
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ski_resort_id, SkiResort.all, :id, :name, {}, {class:"select-box", id:"congestion-ski-resort"}) %>
      <%# /スキー場名 %>
      <%# 状況 %>
        <div class="items-explain">
          <div class="weight-bold-text">
          状況
          <span class="indispensable">任意</span>
          </div>
        <%= f.text_area :situation, class:"situation-text", id:"situation-info", placeholder:"状況の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        </div>
      <%# /状況 %>
      <%# 待ち時間 %>
        <div class="waiting-content">
          <div class="waiting-text">
          待ち時間
          <span class="indispensable">必須</span>
          </div>
        <%= f.text_field :waiting, class:"waiting-input", id:"congestion-waiting", placeholder:"例）60" %>
        <span class="waiting-minutes">分</span>
        </div>
      <%# /待ち時間 %>
      <%# 画像 %><%# /画像 %>
        <div class="img-upload">
          <div class="weight-bold-text">
          画像
          <span class="indispensable">任意</span>
          </div>
          <div class="click-upload">
          <p>クリックしてファイルをアップロード</p>
          <%= f.file_field :image, id:"congestion-image" %>
          </div>
        </div>
  <%# 下部ボタン %>
        <div class="congestion-btn-contents">
          <%= f.submit "投稿する" ,class:"form-btn" %>
          <%=link_to 'もどる', root_path, class:"back-btn" %>
        </div>
  <%# /下部ボタン %>
      <% end %>
      </div>
    </div>
  </div>
</body>

app/views/congestions/index.html.erb
<body>
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="geo-fill" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M4 4a4 4 0 1 1 4.5 3.969V13.5a.5.5 0 0 1-1 0V7.97A4 4 0 0 1 4 3.999zm2.493 8.574a.5.5 0 0 1-.411.575c-.712.118-1.28.295-1.655.493a1.319 1.319 0 0 0-.37.265.301.301 0 0 0-.057.09V14l.002.008a.147.147 0 0 0 .016.033.617.617 0 0 0 .145.15c.165.13.435.27.813.395.751.25 1.82.414 3.024.414s2.273-.163 3.024-.414c.378-.126.648-.265.813-.395a.619.619 0 0 0 .146-.15.148.148 0 0 0 .015-.033L12 14v-.004a.301.301 0 0 0-.057-.09 1.318 1.318 0 0 0-.37-.264c-.376-.198-.943-.375-1.655-.493a.5.5 0 1 1 .164-.986c.77.127 1.452.328 1.957.594C12.5 13 13 13.4 13 14c0 .426-.26.752-.544.977-.29.228-.68.413-1.116.558-.878.293-2.059.465-3.34.465-1.281 0-2.462-.172-3.34-.465-.436-.145-.826-.33-1.116-.558C3.26 14.752 3 14.426 3 14c0-.599.5-1 .961-1.243.505-.266 1.187-.467 1.957-.594a.5.5 0 0 1 .575.411z"></path>
    </symbol>
    <symbol id="alarm-fil" viewBox="0 0 16 16">
      <path d="M6 .5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H9v1.07a7.001 7.001 0 0 1 3.274 12.474l.601.602a.5.5 0 0 1-.707.708l-.746-.746A6.97 6.97 0 0 1 8 16a6.97 6.97 0 0 1-3.422-.892l-.746.746a.5.5 0 0 1-.707-.708l.602-.602A7.001 7.001 0 0 1 7 2.07V1h-.5A.5.5 0 0 1 6 .5zm2.5 5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5zM.86 5.387A2.5 2.5 0 1 1 4.387 1.86 8.035 8.035 0 0 0 .86 5.387zM11.613 1.86a2.5 2.5 0 1 1 3.527 3.527 8.035 8.035 0 0 0-3.527-3.527z"/>
    </symbol>
    <symbol id="calendar3" viewBox="0 0 16 16">
      <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
      <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
    </symbol>
  </svg>
  <script>
    function initMap() {
      <% @congestions.each_with_index do |congestion,i| %>
      var latlng = new google.maps.LatLng(<%= congestion.latitude %>,<%= congestion.longitude %>);
      map = new google.maps.Map(document.getElementById('map<%=i%>'), {
          center: {lat: <%= congestion.latitude %>, lng: <%= congestion.longitude %>},
          zoom: 12
        });
       marker = new google.maps.Marker({
          position: latlng,
          map: map
        });
      <% end %>
    }
  </script>
  <main>
    <div class="container px-4 py-5" id="custom-cards">
      <h2 class="pb-2 border-bottom">Stuck</h2>
      <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
        <% @congestions.each_with_index do |congestion,i| %>
        <div class="col"style='width: 350px; height: 500px;'>
          <div class="card card-cover h-100 w-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg">
            <div class="d-flex flex-column h-100 text-white text-shadow-1">
              <div id="map<%=i%>" style='width: 100%; height: 100%;'></div>
              <div class="d-flex justify-content-around align-items-center">
              <ul class="ul" style="margin-bottom: 0px;padding-left: 0px;">
                <li class="li">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                  <%= congestion.ski_resort.name %>
                </li>
                <li class="li">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#alarm-fil"></use></svg>
                  <%= congestion.waiting %>
                  <span>min</span>
                </li>
                <li class="li">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"></use></svg>
                  <%= congestion.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
                </li>
              </ul>
              <%= link_to congestion_path(congestion.id) do %>
                <button type="button" class="btn btn-light btn-lg">詳細</button>
              <% end %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </main>
</body>

app/views/congestions/show.html.erb
<body>
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="geo-fill" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M4 4a4 4 0 1 1 4.5 3.969V13.5a.5.5 0 0 1-1 0V7.97A4 4 0 0 1 4 3.999zm2.493 8.574a.5.5 0 0 1-.411.575c-.712.118-1.28.295-1.655.493a1.319 1.319 0 0 0-.37.265.301.301 0 0 0-.057.09V14l.002.008a.147.147 0 0 0 .016.033.617.617 0 0 0 .145.15c.165.13.435.27.813.395.751.25 1.82.414 3.024.414s2.273-.163 3.024-.414c.378-.126.648-.265.813-.395a.619.619 0 0 0 .146-.15.148.148 0 0 0 .015-.033L12 14v-.004a.301.301 0 0 0-.057-.09 1.318 1.318 0 0 0-.37-.264c-.376-.198-.943-.375-1.655-.493a.5.5 0 1 1 .164-.986c.77.127 1.452.328 1.957.594C12.5 13 13 13.4 13 14c0 .426-.26.752-.544.977-.29.228-.68.413-1.116.558-.878.293-2.059.465-3.34.465-1.281 0-2.462-.172-3.34-.465-.436-.145-.826-.33-1.116-.558C3.26 14.752 3 14.426 3 14c0-.599.5-1 .961-1.243.505-.266 1.187-.467 1.957-.594a.5.5 0 0 1 .575.411z"></path>
    </symbol>
    <symbol id="alarm-fil" viewBox="0 0 16 16">
      <path d="M6 .5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H9v1.07a7.001 7.001 0 0 1 3.274 12.474l.601.602a.5.5 0 0 1-.707.708l-.746-.746A6.97 6.97 0 0 1 8 16a6.97 6.97 0 0 1-3.422-.892l-.746.746a.5.5 0 0 1-.707-.708l.602-.602A7.001 7.001 0 0 1 7 2.07V1h-.5A.5.5 0 0 1 6 .5zm2.5 5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5zM.86 5.387A2.5 2.5 0 1 1 4.387 1.86 8.035 8.035 0 0 0 .86 5.387zM11.613 1.86a2.5 2.5 0 1 1 3.527 3.527 8.035 8.035 0 0 0-3.527-3.527z"/>
    </symbol>
  </svg>
  <main>
    <div class="container px-4 py-5" id="custom-cards">
      <h2 class="pb-2 border-bottom">詳細状況</h2>
      <p class="solution">
        <% if @congestion.solved_by?(current_user) %>
          <%= link_to congestion_solution_path(@congestion), method: :delete, class: "solution_btn" do %>
          <%= @congestion.solutions.count %>解決
          <% end %>
        <% else %>
          <%= link_to congestion_solutions_path(@congestion), method: :post, class: "solution_btn" do %>
          <%= @congestion.solutions.count %>解決
          <% end %>
        <% end %>
        </p>
      <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <p class="detail__message" style='width: 100%; height: 100px;'><%= @congestion.situation %></p>
        <div class="col" style='width: 100%; height: 100vh;'>
          <div class="card card-cover h-100 w-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg">
            <div class="d-flex flex-column h-100 text-white text-shadow-1">
              <div id="map" style='width: 100%; height:100%;'></div>
              <ul class="d-flex align-items-center justify-content-center"style="padding-left: 0px;margin-bottom: 0px;">
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                  <%= link_to @congestion.ski_resort.name,  congestion_path(@congestion.id), method: :get %>
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#alarm-fil"></use></svg>
                  <%= @congestion.waiting %>
                  <span>min</span>
                <li class="d-flex align-items-center me-3">
                  <%= @congestion.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
                </li>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="congestion__user" style='width: 100%;padding-right: 30px;margin-top: 0px;"'><%= "by " + @congestion.user.nickname %></div>
        </div>
        <div class="congestion__image" style='width: 100%;'>
        <% if @congestion.image.present? %>
          <%= image_tag @congestion.image.variant(resize: '500x500') %>
        <% end %>
        </div>
        <% if user_signed_in? && current_user.id == @congestion.user_id %>
          <div class="congestion__manage d-flex align-items-center" style='width: 100%;'>
            <%= link_to "編集する", edit_congestion_path(@congestion.id), class: :edit__btn %>
            <%= link_to "削除する", congestion_path(@congestion.id), method: :delete, class: :destroy__btn %>
          </div>
        <% end %>
        <div class="congestion__comments" style='width: 100%;'>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理 %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%= link_to comment.user.nickname, "/users/#{comment.user_id}", class: :comment_user%>
              <% if user_signed_in? %>
              <% if current_user.id == comment.user_id %>
                <%=link_to "削除", congestion_comment_path(@congestion, comment), method: :delete %>
              <% end %>
              <% end %>
            </li>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理 %>
        </ul>
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with model: [@congestion, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
<script>
    function initMap() {
      var latlng = new google.maps.LatLng(<%= @congestion.latitude %>,<%= @congestion.longitude %>);
      map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: <%= @congestion.latitude %>, lng: <%= @congestion.longitude %>},
          zoom: 14
        });
       marker = new google.maps.Marker({
          position: latlng,
          map: map
        });
    }

</script>
  </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Avoidstuck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API_KEY']%>&callback=initMap" async defer></script>
  </head>

  <body>
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
      </svg>
      <div class="d-flex flex-wrap align-items-center">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none" style="margin-bottom: 0px;"><img src="https://images.cooltext.com/5630592.png" width="210" height="30" alt="AvoidStuck" /></a>
        <% if user_signed_in? %>
        <ul class="nav col-12 col-lg-auto me-lg-auto">
          <li><a href="/users/<%= current_user.id %>" class="nav-link px-2 text-white">MyPage</a></li>
        </ul>
        <% else %>
        <ul class="nav col-12 col-lg-auto me-lg-auto">
          <li><a href="/users/sign_in" class="nav-link px-2 text-white">MyPage</a></li>
        </ul>
        <% end %>
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>
        <div class="text-end">
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path do %>
              <button type="button" class="btn btn-outline-light me-2">Logout</button>
            <% end %>
            <%= link_to new_congestion_path do %>
              <button type="button" class="btn btn-warning">New Stuck</button>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path do %>
              <button type="button" class="btn btn-outline-light me-2">Login</button>
            <% end %>
            <%= link_to new_user_registration_path do %>
              <button type="button" class="btn btn-warning">Sign-up</button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </header>
    <%= yield %>
  <footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
  </footer>
  </body>
</html>